// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	NickName        string `json:"nickname"`
	Avatar          string `json:"avatar"`
	Gender          int64  `json:"gender"`
	Birthday        string `json:"birthday"`
	Region          string `json:"region"`
	Phone           string `json:"phone"`
	Openid          string `json:"openid"`
	HistoryPoints   int64  `json:"historyPoints"`
	AvailablePoints int64  `json:"availablePoints"`
}

type LoginRes struct {
	LoginCode string `json:"loginCode"`
	Phone     string `json:"phone"`
}

type NoPhoneLoginRes struct {
	LoginCode string `json:"loginCode"`
}

type LoginRp struct {
	Userinfo     *UserInfo `json:"userInfo"`
	LoginSuccess bool      `json:"loginSuccess"`
	IsRebund     bool      `json:"isRebund"`
	IsNew        bool      `json:"isNew"`
	AccessToken  string    `json:"accessToken"`
}

type LoginResp struct {
	Code string   `json:"code"`
	Msg  string   `json:"msg"`
	Data *LoginRp `json:"data"`
}

type GetUserInfoRes struct {
}

type GetUserInfoRp struct {
	Userinfo *UserInfo `json:"userInfo"`
}

type GetUserInfoResp struct {
	Code string         `json:"code"`
	Msg  string         `json:"msg"`
	Data *GetUserInfoRp `json:"data"`
}

type UpdateUserInfoRes struct {
	NickName string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int64  `json:"gender"`
	Birthday string `json:"birthday"`
	Region   string `json:"region"`
}

type UpdateUserInfoRp struct {
	Userinfo *UserInfo `json:"userInfo"`
}

type UpdateUserInfoResp struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Data *UpdateUserInfoRp `json:"data"`
}

type ReboundRes struct {
	LoginCode string `json:"loginCode"`
}

type ReboundRp struct {
	Userinfo     *UserInfo `json:"userInfo"`
	AccessToken  string    `json:"accessToken"`
	AccessExpire string    `json:"accessExpire"`
	RefreshAfter string    `json:"refreshAfter"`
}

type ReboundResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data *ReboundRp `json:"data"`
}

type RefreshRes struct {
	Force bool `json:"force"`
}

type RefreshResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type GetPhoneRes struct {
	PhoneCode string `json:"phoneCode"`
}

type GetPhoneRp struct {
	Phone       string `json:"phone"`
	CountryCode string `json:"countryCode"`
}

type GetPhoneResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *GetPhoneRp `json:"data"`
}

type WaterMark struct {
	Timestamp int64  `json:"timestamp"`
	Appid     string `json:"appid"`
}

type PhoneInfo struct {
	PhoneNumber     string     `json:"phoneNumber"`
	PurePhoneNumber string     `json:"purePhoneNumber"`
	CountryCode     string     `json:"countryCode"`
	Watermark       *WaterMark `json:"watermark"`
}

type PhoneStruct struct {
	Errcode   int        `json:"errcode"`
	Errmsg    string     `json:"errmsg"`
	Phoneinfo *PhoneInfo `json:"phone_info"`
}

type MsgData struct {
	OrderKey       *OrderKey       `json:"order_key"`
	LogisticsType  int64           `json:"logistics_type"`
	DeliveryMode   int64           `json:"delivery_mode"`
	IsAllDelivered bool            `json:"is_all_delivered"`
	ShippingList   []*ShippingList `json:"shipping_list"`
	UploadTime     string          `json:"upload_time"`
	Payer          *Payer          `json:"payer"`
}

type Payer struct {
	Openid string `json:"openid"`
}

type OrderKey struct {
	OrderNumberType int64  `json:"order_number_type"`
	TransactionId   string `json:"transaction_id"`
	Mchid           string `json:"mchid"`
	OutTradeNo      string `json:"out_trade_no"`
}

type ShippingList struct {
	TrackingNo     string   `json:"tracking_no"`
	ExpressCompany string   `json:"express_company"`
	ItemDesc       string   `json:"item_desc"`
	Contact        *Contact `json:"contact"`
}

type Contact struct {
	ConsignorContact string `json:"consignor_contact"`
	ReceiverContact  string `json:"receiver_contact"`
}

type MsgDelivering struct {
	TransactionId   string `json:"transaction_id"`
	MerchantId      string `json:"merchant_id"`
	SubMerchantId   string `json:"sub_merchant_id"`
	MerchantTradeNo string `json:"merchant_trade_no"`
}

type MsgReturn struct {
	Errcode int64  `json:"errcode"`
	Errmsg  string `json:"errmsg"`
	Order   *Order `json:"order"`
}

type Order struct {
	TransactionId string `json:"transaction_id"`
	OrderState    int64  `json:"order_state"`
	Openid        string `json:"openid"`
}
