// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	NickName   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	Gender     int    `json:"gender"`
	Birthday   string `json:"birthday"`
	Region     string `json:"region"`
	Phone      string `json:"phone"`
	Openid     string `json:"openid"`
	Wechatbind int    `json:"wechatbind"`
	Effective  int    `json:"effective"`
}

type LoginRes struct {
	LoginCode string `json:"loginCode"`
}

type LoginRp struct {
	Userinfo     UserInfo `json:"userInfo"`
	IsNew        int      `json:"isNew"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire string   `json:"accessExpire"`
	RefreshAfter string   `json:"refreshAfter"`
}

type LoginResp struct {
	Code string  `json:"code"`
	Msg  string  `json:"msg"`
	Data LoginRp `json:"data"`
}

type GetUserInfoRes struct {
	Phone  string `json:"phone"`
	Openid string `json:"openid"` // 我会优先用openid查找，找不到再用phone去查
}

type GetUserInfoRp struct {
	Userinfo UserInfo `json:"userInfo"`
}

type GetUserInfoResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data GetUserInfoRp `json:"data"`
}

type UpdateUserInfoRes struct {
	Openid     string `json:"openid"`
	NickName   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	Gender     int    `json:"gender"`
	Birthday   string `json:"birthday"`
	Region     string `json:"region"`
	Phone      string `json:"phone"`
	Wechatbind int    `json:"wechatbind"`
	Effective  int    `json:"effective"`
}

type UpdateUserInfoRp struct {
	Userinfo UserInfo `json:"userInfo"`
}

type UpdateUserInfoResp struct {
	Code string           `json:"code"`
	Msg  string           `json:"msg"`
	Data UpdateUserInfoRp `json:"data"`
}
