// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	NickName string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int64  `json:"gender"`
	Birthday string `json:"birthday"`
	Region   string `json:"region"`
	Phone    string `json:"phone"`
	Openid   string `json:"openid"`
}

type LoginRes struct {
	LoginCode string `json:"loginCode"`
	Phone     string `json:"phone"`
}

type LoginRp struct {
	Userinfo     UserInfo `json:"userInfo"`
	IsNew        int      `json:"isNew"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire string   `json:"accessExpire"`
	RefreshAfter string   `json:"refreshAfter"`
}

type LoginResp struct {
	Code string  `json:"code"`
	Msg  string  `json:"msg"`
	Data LoginRp `json:"data"`
}

type GetUserInfoRes struct {
	Phone  string `json:"phone"`
	Openid string `json:"openid"` // 我会优先用openid查找，找不到再用phone去查
}

type GetUserInfoRp struct {
	Userinfo UserInfo `json:"userInfo"`
}

type GetUserInfoResp struct {
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
	Data GetUserInfoRp `json:"data"`
}

type UpdateUserInfoRes struct {
	Openid   string `json:"openid"`
	NickName string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int64  `json:"gender"`
	Birthday string `json:"birthday"`
	Region   string `json:"region"`
	Phone    string `json:"phone"`
}

type UpdateUserInfoRp struct {
	Userinfo UserInfo `json:"userInfo"`
}

type UpdateUserInfoResp struct {
	Code string           `json:"code"`
	Msg  string           `json:"msg"`
	Data UpdateUserInfoRp `json:"data"`
}

type UnboundRp struct {
	Userinfo     UserInfo `json:"userInfo"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire string   `json:"accessExpire"`
	RefreshAfter string   `json:"refreshAfter"`
}

type UnboundResp struct {
	Code string    `json:"code"`
	Msg  string    `json:"msg"`
	Data UnboundRp `json:"data"`
}

type RefreshRes struct {
	Force bool `json:"force"`
}

type RefreshResp struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type GetPhoneRes struct {
	PhoneCode string `json:"phoneCode"`
}

type GetPhoneRp struct {
	Phone       string `json:"phone"`
	CountryCode string `json:"countryCode"`
}

type GetPhoneResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data *GetPhoneRp `json:"data"`
}

type WaterMark struct {
	Timestamp int64  `json:"timestamp"`
	Appid     string `json:"appid"`
}

type PhoneInfo struct {
	PhoneNumber     string     `json:"phoneNumber"`
	PurePhoneNumber string     `json:"purePhoneNumber"`
	CountryCode     string     `json:"countryCode"`
	Watermark       *WaterMark `json:"watermark"`
}

type PhoneStruct struct {
	Errcode   int        `json:"errcode"`
	Errmsg    string     `json:"errmsg"`
	Phoneinfo *PhoneInfo `json:"phone_info"`
}
