// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	myuser "author/internal/handler/myuser"
	"author/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: myuser.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getinfo",
				Handler: myuser.GetinfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateinfo",
				Handler: myuser.UpdateinfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unbound",
				Handler: myuser.UnboundHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
	)
}
