// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userinfosFieldNames          = builder.RawFieldNames(&Userinfos{})
	userinfosRows                = strings.Join(userinfosFieldNames, ",")
	userinfosRowsExpectAutoSet   = strings.Join(stringx.Remove(userinfosFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userinfosRowsWithPlaceHolder = strings.Join(stringx.Remove(userinfosFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheDevUserinfosIdPrefix     = "cache:dev:userinfos:id:"
	cacheDevUserinfosOpenidPrefix = "cache:dev:userinfos:openid:"
	cacheDevUserinfosPhonePrefix  = "cache:dev:userinfos:phone:"
)

type NullTime struct {
	Time  time.Time
	Valid bool // Valid is true if Time is not NULL
}

func ToNullTime(t time.Time) NullTime {
	return NullTime{Time: t, Valid: !t.IsZero()}
}

type (
	userinfosModel interface {
		Insert(ctx context.Context, data *Userinfos) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Userinfos, error)
		FindOneByOpenid(ctx context.Context, openid string) (*Userinfos, error)
		FindOneByPhone(ctx context.Context, phone string) (*Userinfos, error)
		Update(ctx context.Context, data *Userinfos) error
		UpdateByOpenid(ctx context.Context, data *Userinfos) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserinfosModel struct {
		sqlc.CachedConn
		table string
	}

	Userinfos struct {
		Id         uint64       `db:"id"`
		CreatedAt  sql.NullTime `db:"created_at"`
		UpdatedAt  sql.NullTime `db:"updated_at"`
		DeletedAt  sql.NullTime `db:"deleted_at"`
		NickName   string       `db:"nick_name"`
		Avatar     string       `db:"avatar"`
		Gender     int64        `db:"gender"`
		Birthday   string       `db:"birthday"`
		Region     string       `db:"region"`
		Phone      string       `db:"phone"`
		Openid     string       `db:"openid"`
		Wechatbind int64        `db:"wechatbind"`
		Effective  int64        `db:"effective"`
	}
)

func newUserinfosModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserinfosModel {
	return &defaultUserinfosModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`userinfos`",
	}
}

func (m *defaultUserinfosModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	devUserinfosIdKey := fmt.Sprintf("%s%v", cacheDevUserinfosIdPrefix, id)
	devUserinfosOpenidKey := fmt.Sprintf("%s%v", cacheDevUserinfosOpenidPrefix, data.Openid)
	devUserinfosPhoneKey := fmt.Sprintf("%s%v", cacheDevUserinfosPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, devUserinfosIdKey, devUserinfosOpenidKey, devUserinfosPhoneKey)
	return err
}

func (m *defaultUserinfosModel) FindOne(ctx context.Context, id uint64) (*Userinfos, error) {
	devUserinfosIdKey := fmt.Sprintf("%s%v", cacheDevUserinfosIdPrefix, id)
	var resp Userinfos
	err := m.QueryRowCtx(ctx, &resp, devUserinfosIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userinfosRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserinfosModel) FindOneByOpenid(ctx context.Context, openid string) (*Userinfos, error) {
	devUserinfosOpenidKey := fmt.Sprintf("%s%v", cacheDevUserinfosOpenidPrefix, openid)
	var resp Userinfos
	err := m.QueryRowIndexCtx(ctx, &resp, devUserinfosOpenidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `openid` = ? limit 1", userinfosRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, openid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserinfosModel) FindOneByPhone(ctx context.Context, phone string) (*Userinfos, error) {
	devUserinfosPhoneKey := fmt.Sprintf("%s%v", cacheDevUserinfosPhonePrefix, phone)
	var resp Userinfos
	err := m.QueryRowIndexCtx(ctx, &resp, devUserinfosPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userinfosRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultUserinfosModel) Insert(ctx context.Context, data *Userinfos) (sql.Result, error) {
	devUserinfosIdKey := fmt.Sprintf("%s%v", cacheDevUserinfosIdPrefix, data.Id)
	devUserinfosOpenidKey := fmt.Sprintf("%s%v", cacheDevUserinfosOpenidPrefix, data.Openid)
	devUserinfosPhoneKey := fmt.Sprintf("%s%v", cacheDevUserinfosPhonePrefix, data.Phone)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userinfosRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.NickName, data.Avatar, data.Gender, data.Birthday, data.Region, data.Phone, data.Openid, data.Wechatbind, data.Effective)
	}, devUserinfosIdKey, devUserinfosOpenidKey, devUserinfosPhoneKey)
	return ret, err
}

func (m *defaultUserinfosModel) Update(ctx context.Context, newData *Userinfos) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	devUserinfosIdKey := fmt.Sprintf("%s%v", cacheDevUserinfosIdPrefix, data.Id)
	devUserinfosOpenidKey := fmt.Sprintf("%s%v", cacheDevUserinfosOpenidPrefix, data.Openid)
	devUserinfosPhoneKey := fmt.Sprintf("%s%v", cacheDevUserinfosPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userinfosRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreatedAt, newData.UpdatedAt, newData.DeletedAt, newData.NickName, newData.Avatar, newData.Gender, newData.Birthday, newData.Region, newData.Phone, newData.Openid, newData.Wechatbind, newData.Effective, newData.Id)
	}, devUserinfosIdKey, devUserinfosOpenidKey, devUserinfosPhoneKey)
	return err
}
func (m *defaultUserinfosModel) UpdateByOpenid(ctx context.Context, newData *Userinfos) error {

	data, err := m.FindOneByOpenid(ctx, newData.Openid)

	if err != nil {
		return err
	}

	devUserinfosIdKey := fmt.Sprintf("%s%v", cacheDevUserinfosIdPrefix, data.Id)
	devUserinfosOpenidKey := fmt.Sprintf("%s%v", cacheDevUserinfosOpenidPrefix, data.Openid)
	devUserinfosPhoneKey := fmt.Sprintf("%s%v", cacheDevUserinfosPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userinfosRowsWithPlaceHolder)
		newData.UpdatedAt = sql.NullTime(ToNullTime(time.Now()))
		newData.Id = data.Id
		newData.CreatedAt = data.CreatedAt
		return conn.ExecCtx(ctx, query, newData.CreatedAt, newData.UpdatedAt, newData.DeletedAt, newData.NickName, newData.Avatar, newData.Gender, newData.Birthday, newData.Region, newData.Phone, newData.Openid, newData.Wechatbind, newData.Effective, newData.Id)
	}, devUserinfosIdKey, devUserinfosOpenidKey, devUserinfosPhoneKey)
	return err
}

func (m *defaultUserinfosModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDevUserinfosIdPrefix, primary)
}

func (m *defaultUserinfosModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userinfosRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserinfosModel) tableName() string {
	return m.table
}
