// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBehaviourLogFieldNames          = builder.RawFieldNames(&UserBehaviourLog{})
	userBehaviourLogRows                = strings.Join(userBehaviourLogFieldNames, ",")
	userBehaviourLogRowsExpectAutoSet   = strings.Join(stringx.Remove(userBehaviourLogFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userBehaviourLogRowsWithPlaceHolder = strings.Join(stringx.Remove(userBehaviourLogFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userBehaviourLogModel interface {
		Insert(ctx context.Context, data *UserBehaviourLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserBehaviourLog, error)
		Update(ctx context.Context, data *UserBehaviourLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserBehaviourLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserBehaviourLog struct {
		Id        int64     `db:"id"`
		Phone     string    `db:"phone"`     // 手机号账号
		Behaviour string    `db:"behaviour"` // 行为
		Date      time.Time `db:"date"`      // 日志时间
	}
)

func newUserBehaviourLogModel(conn sqlx.SqlConn) *defaultUserBehaviourLogModel {
	return &defaultUserBehaviourLogModel{
		conn:  conn,
		table: "`user_behaviour_log`",
	}
}

func (m *defaultUserBehaviourLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserBehaviourLogModel) FindOne(ctx context.Context, id int64) (*UserBehaviourLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBehaviourLogRows, m.table)
	var resp UserBehaviourLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBehaviourLogModel) Insert(ctx context.Context, data *UserBehaviourLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userBehaviourLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Behaviour, data.Date)
	return ret, err
}

func (m *defaultUserBehaviourLogModel) Update(ctx context.Context, data *UserBehaviourLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userBehaviourLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Behaviour, data.Date, data.Id)
	return err
}

func (m *defaultUserBehaviourLogModel) tableName() string {
	return m.table
}
