// Code generated by goctl. DO NOT EDIT!

package cachemodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBehaviourLogFieldNames          = builder.RawFieldNames(&UserBehaviourLog{})
	userBehaviourLogRows                = strings.Join(userBehaviourLogFieldNames, ",")
	userBehaviourLogRowsExpectAutoSet   = strings.Join(stringx.Remove(userBehaviourLogFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userBehaviourLogRowsWithPlaceHolder = strings.Join(stringx.Remove(userBehaviourLogFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheDevUserBehaviourLogIdPrefix = "cache:dev:userBehaviourLog:id:"
)

type (
	userBehaviourLogModel interface {
		Insert(ctx context.Context, data *UserBehaviourLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserBehaviourLog, error)
		Update(ctx context.Context, data *UserBehaviourLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserBehaviourLogModel struct {
		sqlc.CachedConn
		table string
	}

	UserBehaviourLog struct {
		Id        int64     `db:"id"`
		Phone     string    `db:"phone"`
		Behaviour string    `db:"behaviour"`
		Date      time.Time `db:"date"`
	}
)

func newUserBehaviourLogModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserBehaviourLogModel {
	return &defaultUserBehaviourLogModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_behaviour_log`",
	}
}

func (m *defaultUserBehaviourLogModel) Delete(ctx context.Context, id int64) error {
	devUserBehaviourLogIdKey := fmt.Sprintf("%s%v", cacheDevUserBehaviourLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, devUserBehaviourLogIdKey)
	return err
}

func (m *defaultUserBehaviourLogModel) FindOne(ctx context.Context, id int64) (*UserBehaviourLog, error) {
	devUserBehaviourLogIdKey := fmt.Sprintf("%s%v", cacheDevUserBehaviourLogIdPrefix, id)
	var resp UserBehaviourLog
	err := m.QueryRowCtx(ctx, &resp, devUserBehaviourLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBehaviourLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBehaviourLogModel) Insert(ctx context.Context, data *UserBehaviourLog) (sql.Result, error) {
	devUserBehaviourLogIdKey := fmt.Sprintf("%s%v", cacheDevUserBehaviourLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userBehaviourLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Phone, data.Behaviour, data.Date)
	}, devUserBehaviourLogIdKey)
	return ret, err
}

func (m *defaultUserBehaviourLogModel) Update(ctx context.Context, data *UserBehaviourLog) error {
	devUserBehaviourLogIdKey := fmt.Sprintf("%s%v", cacheDevUserBehaviourLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userBehaviourLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Phone, data.Behaviour, data.Date, data.Id)
	}, devUserBehaviourLogIdKey)
	return err
}

func (m *defaultUserBehaviourLogModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDevUserBehaviourLogIdPrefix, primary)
}

func (m *defaultUserBehaviourLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBehaviourLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserBehaviourLogModel) tableName() string {
	return m.table
}
